---
- name: apt - Add keys for repos using direct url.
  when:
    aspects_packages_add_repo_apt_repos is defined and
    item.value.key_url is defined
  apt_key:
    url: "{{ item.value.key_url }}"
  with_dict: "{{ aspects_packages_add_repo_apt_repos }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

- name: apt - Add keys for repos using keyserver and id.
  when:
    aspects_packages_add_repo_apt_repos is defined and
    item.value.keyserver is defined
  apt_key:
    keyserver: "{{ item.value.keyserver }}"
    id: "{{ item.value.key_id }}"
  with_dict: "{{ aspects_packages_add_repo_apt_repos }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

- name: apt - Add extra repos
  when: aspects_packages_add_repo_apt_repos is defined
  apt_repository:
    repo: "{{ item.value.repo }}"
  with_dict: "{{ aspects_packages_add_repo_apt_repos }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

