---
- name: apt - Add keys for repos using direct url.
  when:
    - aspects_packages_add_repo_apt_repos is defined
    - item.value.enabled
    - item.value.key_url is defined
  apt_key:
    state: "present"
    url: "{{ item.value.key_url }}"
  loop: "{{ aspects_packages_add_repo_apt_repos|dict2items }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

- name: apt - Add keys for repos using keyserver and id.
  when:
    - aspects_packages_add_repo_apt_repos is defined
    - item.value.enabled
    - item.value.keyserver is defined
  apt_key:
    state: "present"
    keyserver: "{{ item.value.keyserver }}"
    id: "{{ item.value.key_id }}"
  loop: "{{ aspects_packages_add_repo_apt_repos|dict2items }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

- name: apt - Add keys for repos using data.
  when:
    - aspects_packages_add_repo_apt_repos is defined
    - item.value.enabled
    - item.value.data is defined
  apt_key:
    state: "present"
    data: "{{ item.value.data }}"
  loop: "{{ aspects_packages_add_repo_apt_repos|dict2items }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

- name: apt - Add extra repos
  when:
    - aspects_packages_add_repo_apt_repos is defined
    - item.value.enabled
    - item.value.repo is defined
  apt_repository:
    repo: "{{ item.value.repo }}"
  loop: "{{ aspects_packages_add_repo_apt_repos|dict2items }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt

