---
- name: Ubuntu 18.04 - apt - Add keys for repos using direct url
  when:
    - ansible_lsb.codename == "bionic"
  apt_key:
    state: "present"
    url: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_url.Ubuntu.1804', 'defined')
              | list
              | map(attribute='value.key_url.Ubuntu.1804')
              | list
          }}"
  register: inprocess_task_result_key_url_bionic
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 20.04 - apt - Add keys for repos using direct url
  when:
    - ansible_lsb.codename == "focal"
  apt_key:
    state: "present"
    url: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_url.Ubuntu.2004', 'defined')
              | list
              | map(attribute='value.key_url.Ubuntu.2004')
              | list
          }}"
  register: inprocess_task_result_key_url_focal
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 22.04 - apt - Add keys for repos using direct url
  when:
    - ansible_lsb.codename == "jammy"
  apt_key:
    state: "present"
    url: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_url.Ubuntu.2204', 'defined')
              | list
              | map(attribute='value.key_url.Ubuntu.2204')
              | list
          }}"
  register: inprocess_task_result_key_url_jammy
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 22.04 - apt - Add keys v2 for repos using direct url
  when:
    - ansible_lsb.codename == "jammy"
  get_url:
    url: "{{ item.value.Ubuntu.2204.key_url }}"
    dest: "{{ item.value.Ubuntu.2204.key_dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ aspects_packages_add_repo_apt_keys | default({}) | dict2items }}"
  register: inprocess_task_result_key_url_v2_jammy
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Debian 10 - apt - Add keys for repos using direct url
  when:
    - ansible_lsb.codename == "buster"
  apt_key:
    state: "present"
    url: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_url.Debian.10', 'defined')
              | list
              | map(attribute='value.key_url.Debian.10')
              | list | sort
          }}"
  register: inprocess_task_result_key_url_buster
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 18.04 - apt - Add keys for repos using keyserver and id.
  when:
    - ansible_lsb.codename == "bionic"
  apt_key:
    state: "present"
    keyserver: "{{ item.value.keyserver.Ubuntu.1804 }}"
    id: "{{ item.value.key_id.Ubuntu.1804 }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_id.Ubuntu.1804', 'defined')
              | selectattr('value.keyserver.Ubuntu.1804', 'defined')
              | list | sort
        }}"
  register: inprocess_task_result_key_id_bionic
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 20.04 - apt - Add keys for repos using keyserver and id.
  when:
    - ansible_lsb.codename == "focal"
  apt_key:
    state: "present"
    keyserver: "{{ item.value.keyserver.Ubuntu.2004 }}"
    id: "{{ item.value.key_id.Ubuntu.2004 }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_id.Ubuntu.2004', 'defined')
              | selectattr('value.keyserver.Ubuntu.2004', 'defined')
              | list | sort
        }}"
  register: inprocess_task_result_key_id_focal
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 22.04 - apt - Add keys for repos using keyserver and id.
  when:
    - ansible_lsb.codename == "jammy"
  apt_key:
    state: "present"
    keyserver: "{{ item.value.keyserver.Ubuntu.2204 }}"
    id: "{{ item.value.key_id.Ubuntu.2204 }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_id.Ubuntu.2204', 'defined')
              | selectattr('value.keyserver.Ubuntu.2204', 'defined')
              | list | sort
        }}"
  register: inprocess_task_result_key_id_jammy
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Debian 10 - apt - Add keys for repos using keyserver and id.
  when:
    - ansible_lsb.codename == "buster"
  apt_key:
    state: "present"
    keyserver: "{{ item.value.keyserver.Debian.10 }}"
    id: "{{ item.value.key_id.Debian.10 }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.key_id.Debian.10', 'defined')
              | selectattr('value.keyserver.Debian.10', 'defined')
              | list | sort
        }}"
  register: inprocess_task_result_key_id_buster
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 18.04 - apt - Add keys for repos using data
  when:
    - ansible_lsb.codename == "bionic"
  apt_key:
    state: "present"
    data: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.data.Ubuntu.1804', 'defined')
              | list
              | map(attribute='value.data.Ubuntu.1804')
              | list | sort
          }}"
  register: inprocess_task_result_key_data_bionic
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 20.04 - apt - Add keys for repos using data
  when:
    - ansible_lsb.codename == "focal"
  apt_key:
    state: "present"
    data: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.data.Ubuntu.2004', 'defined')
              | list
              | map(attribute='value.data.Ubuntu.2004')
              | list | sort
          }}"
  register: inprocess_task_result_key_data_focal
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 22.04 - apt - Add keys for repos using data
  when:
    - ansible_lsb.codename == "jammy"
  apt_key:
    state: "present"
    data: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.data.Ubuntu.2204', 'defined')
              | list
              | map(attribute='value.data.Ubuntu.2204')
              | list | sort
          }}"
  register: inprocess_task_result_key_data_jammy
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Debian 10 - apt - Add keys for repos using data
  when:
    - ansible_lsb.codename == "buster"
  apt_key:
    state: "present"
    data: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.data.Debian.10', 'defined')
              | list
              | map(attribute='value.data.Debian.10')
              | list | sort
          }}"
  register: inprocess_task_result_key_data_buster
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 18.04 - apt - Add extra repos
  when:
    - ansible_lsb.codename == "bionic"
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.repo.Ubuntu.1804', 'defined')
              | list
              | map(attribute='value.repo.Ubuntu.1804')
              | list | sort
          }}"
  register: inprocess_task_result_repo_bionic
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 20.04 - apt - Add extra repos
  when:
    - ansible_lsb.codename == "focal"
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.repo.Ubuntu.2004', 'defined')
              | list
              | map(attribute='value.repo.Ubuntu.2004')
              | list | sort
          }}"
  register: inprocess_task_result_repo_focal
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Ubuntu 22.04 - apt - Add extra repos
  when:
    - ansible_lsb.codename == "jammy"
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.repo.Ubuntu.2204', 'defined')
              | list
              | map(attribute='value.repo.Ubuntu.2204')
              | list | sort
          }}"
  register: inprocess_task_result_repo_jammy
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: Debian 10 - apt - Add extra repos
  when:
    - ansible_lsb.codename == "buster"
  apt_repository:
    repo: "{{ item }}"
  loop: "{{ aspects_packages_add_repo_apt_repos
              | default({}) | dict2items
              | selectattr('value.enabled', 'eq', True)
              | selectattr('value.repo.Debian.10', 'defined')
              | list
              | map(attribute='value.repo.Debian.10')
              | list | sort
          }}"
  register: inprocess_task_result_repo_buster
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: "Update apt cache when a new key and/or repo is added."
  when: (
    inprocess_task_result_key_url_bionic.changed
    or inprocess_task_result_key_url_focal.changed
    or inprocess_task_result_key_url_jammy.changed
    or inprocess_task_result_key_url_buster.changed
    or inprocess_task_result_key_id_bionic.changed
    or inprocess_task_result_key_id_focal.changed
    or inprocess_task_result_key_id_jammy.changed
    or inprocess_task_result_key_id_buster.changed
    or inprocess_task_result_key_data_bionic.changed
    or inprocess_task_result_key_data_focal.changed
    or inprocess_task_result_key_data_jammy.changed
    or inprocess_task_result_key_data_buster.changed
    or inprocess_task_result_repo_bionic.changed
    or inprocess_task_result_repo_focal.changed
    or inprocess_task_result_repo_jammy.changed
    or inprocess_task_result_repo_buster.changed
    )
  shell: "apt-get update"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt
