## Start install aspects_packages_prerequisite_packages
- name: install Ubuntu 18.04 prerequisite packages with state present
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop" 
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_bionic_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 20.04 prerequisite packages with state present
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop" 
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_focal_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 9 prerequisite packages with state present
  when:
    - ansible_lsb.codename == "stretch"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list | sort }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_stretch_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 10 prerequisite packages with state present
  when:
    - ansible_lsb.codename == "buster"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_buster_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 18.04 prerequisite packages with state latest
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop" 
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_bionic_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 20.04 prerequisite packages with state latest
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop" 
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_focal_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 9 prerequisite packages with state latest
  when:
    - ansible_lsb.codename == "stretch"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list | sort }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_stretch_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 10 prerequisite packages with state latest
  when:
    - ansible_lsb.codename == "buster"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_prerequisite_buster_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_bionic_result_present
  when: inprocess_prerequisite_bionic_result_present.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_focal_result_present
  when: inprocess_prerequisite_focal_result_present.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_stretch_result_present
  when: inprocess_prerequisite_stretch_result_present.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_bionic_result_latest
  when: inprocess_prerequisite_bionic_result_latest.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_focal_result_latest
  when: inprocess_prerequisite_focal_result_latest.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_stretch_result_latest
  when: inprocess_prerequisite_stretch_result_latest.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of prerequisite packages when change occurs inprocess_prerequisite_buster_result_latest
  when: inprocess_prerequisite_buster_result_latest.changed
  debug:
    msg: "{{ aspects_packages_prerequisite_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt
## End install aspects_packages_prerequisite_packages