---
- name: install Ubuntu 16.04 packages with state present
  when:
    - ansible_lsb.codename == "xenial"
    - ansible_lsb.id == "Ubuntu"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1604', 'defined') | list | map(attribute='value.Ubuntu.1604') | list }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_xenial_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 18.04 packages with state present
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_bionic_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 20.04 packages with state present
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_focal_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 9 packages with state present
  when:
    - ansible_lsb.codename == "stretch"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list }}"
    state: "present"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_stretch_result_present
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 16.04 packages with state latest
  when:
    - ansible_lsb.codename == "xenial"
    - ansible_lsb.id == "Ubuntu"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1604', 'defined') | list | map(attribute='value.Ubuntu.1604') | list }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_xenial_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 18.04 packages with state latest
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_bionic_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Ubuntu 20.04 packages with state latest
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop" 
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_focal_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: install Debian 9 packages with state latest
  when:
    - ansible_lsb.codename == "stretch"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list }}"
    state: "latest"
    update_cache: "yes"
    cache_valid_time: "14400"
  register: inprocess_stretch_result_latest
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_xenial_result_present
  when: inprocess_xenial_result_present.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1604', 'defined') | list | map(attribute='value.Ubuntu.1604') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_bionic_result_present
  when: inprocess_bionic_result_present.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_focal_result_present
  when: inprocess_focal_result_present.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_stretch_result_present
  when: inprocess_stretch_result_present.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'present') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_xenial_result_latest
  when: inprocess_xenial_result_latest.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1604', 'defined') | list | map(attribute='value.Ubuntu.1604') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_bionic_result_latest
  when: inprocess_bionic_result_latest.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_focal_result_latest
  when: inprocess_focal_result_latest.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_stretch_result_latest
  when: inprocess_stretch_result_latest.changed
  debug:
    msg: "{{ aspects_packages_packages | dict2items | selectattr('value.state', 'eq', 'latest') | selectattr('value.Debian.9', 'defined') | list | map(attribute='value.Debian.9') | list }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt
