---
## Start remove aspects_packages_packages
- name: remove Ubuntu 18.04 packages with state absent
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
    state: "absent"
  register: inprocess_bionic_result_absent
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Ubuntu 20.04 packages with state absent
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
    state: "absent"
  register: inprocess_focal_result_absent
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Ubuntu 22.04 packages with state absent
  when:
    - ansible_lsb.codename == "jammy"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.2204', 'defined') | list | map(attribute='value.Ubuntu.2204') | list | sort }}"
    state: "absent"
  register: inprocess_jammy_result_absent
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Debian 10 packages with state absent
  when:
    - ansible_lsb.codename == "buster"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
    state: "absent"
  register: inprocess_buster_result_absent
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Ubuntu 18.04 packages with state purged
  when:
    - ansible_lsb.codename == "bionic"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
    state: "absent"
    purge: "yes"
  register: inprocess_bionic_result_purged
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Ubuntu 20.04 packages with state purged
  when:
    - ansible_lsb.codename == "focal"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
    state: "absent"
    purge: "yes"
  register: inprocess_focal_result_purged
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Ubuntu 22.04 packages with state purged
  when:
    - ansible_lsb.codename == "jammy"
    - ansible_lsb.id == "Ubuntu" or ansible_lsb.id == "Pop"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.2204', 'defined') | list | map(attribute='value.Ubuntu.2204') | list | sort }}"
    state: "absent"
    purge: "yes"
  register: inprocess_jammy_result_purged
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: remove Debian 10 packages with state purged
  when:
    - ansible_lsb.codename == "buster"
    - ansible_lsb.id == "Debian"
  apt:
    pkg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
    state: "absent"
    purge: "yes"
  register: inprocess_buster_result_purged
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_bionic_result_absent
  when: inprocess_bionic_result_absent.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_focal_result_absent
  when: inprocess_focal_result_absent.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_jammy_result_absent
  when: inprocess_jammy_result_absent.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Ubuntu.2204', 'defined') | list | map(attribute='value.Ubuntu.2204') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_buster_result_absent
  when: inprocess_buster_result_absent.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'absent ') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_bionic_result_purged
  when: inprocess_bionic_result_purged.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.1804', 'defined') | list | map(attribute='value.Ubuntu.1804') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_focal_result_purged
  when: inprocess_focal_result_purged.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.2004', 'defined') | list | map(attribute='value.Ubuntu.2004') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_jammy_result_purged
  when: inprocess_jammy_result_purged.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Ubuntu.2204', 'defined') | list | map(attribute='value.Ubuntu.2204') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt

- name: Log list of packages when change occurs inprocess_buster_result_purged
  when: inprocess_buster_result_purged.changed
  debug:
    msg: "{{ aspects_packages_packages | default({}) | dict2items | selectattr('value.state', 'eq', 'purged') | selectattr('value.Debian.10', 'defined') | list | map(attribute='value.Debian.10') | list | sort }}"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt
## End remove aspects_packages_packages