---
- name: "add repositories"
  when: aspects_packages_add_repo_apt_repos is defined or aspects_packages_add_repo_yum_repos is defined
  include_tasks: "{{ ansible_pkg_mgr }}AddRepository.yml"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt
    - aspects_packages_add_repo_yum

- name: "install packages"
  include_tasks: "{{ ansible_pkg_mgr }}InstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_prerequisite_package_install

- name: "remove packages"
  include_tasks: "{{ ansible_pkg_mgr }}RemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_remove

- name: "Install pip packages"
  when: aspects_packages_pip_enabled
  include_tasks: "pipInstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_pip
    - aspects_packages_package_install
    - aspects_packages_package_install_pip

- name: "Remove pip packages"
  when: aspects_packages_pip_enabled
  include_tasks: "pipRemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_pip
    - aspects_packages_package_remove
    - aspects_packages_package_remove_pip