---
- name: "APT - Ubuntu - Template /etc/apt/sources.list"
  when:
    - ansible_pkg_mgr == "apt"
    - ( ansible_lsb.codename == "bionic"
        or ansible_lsb.codename == "focal" )
    - ( aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_src.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_src.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_src.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_src.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_src_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_src_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_src_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_src_updates.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_src_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_src_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_src_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_src_backports.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_main_src_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_restricted_src_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_universe_src_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_src_security.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_partner.enabled
        or aspects_packages_add_repo_apt_repos.ubuntu_official_mirrors_multiverse_src_partner.enabled )
  template:
    src: "etc-apt-sources.list.j2"
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - aspects_packages

- name: "APT - add repositories"
  when:
    - ansible_pkg_mgr == "apt"
    - aspects_packages_add_repo_apt_repos is defined
  include_tasks: "aptAddRepository.yml"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: "APT - remove prerequisite packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptRemovePrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_remove

- name: "YUM/DNF - remove prerequisite packages"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
  include_tasks: "yumRemovePrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_remove

- name: "APT - remove packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptRemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_remove

- name: "YUM/DNF - remove packages"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
  include_tasks: "yumRemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_remove

- name: "APT - install prerequisite packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptInstallPrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_install

- name: "YUM/DNF - install prerequisite packages"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
  include_tasks: "yumInstallPrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_install

- name: "YUM/DNF - add repositories"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
    - aspects_packages_add_repo_yum_repos is defined
  include_tasks: "yumAddRepository.yml"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_yum

- name: "APT - install packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptInstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_install

- name: "YUM/DNF - install packages"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
  include_tasks: "yumInstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_install

- name: "APT - include installing from url tasks"
  when:
    - ansible_pkg_mgr == "apt"
    - aspects_packages_package_urls is defined
  include_tasks: aptInstallPackageFromUrl.yml
  tags:
    - aspects_packages
    - aspects_packages_package_install
    - aspects_packages_package_install_apt
    - aspects_packages_package_install_apt_url
