---
- name: "APT - install prerequisite packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptInstallPrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_install

- name: "YUM - install prerequisite packages"
  when:
    - ansible_pkg_mgr == "yum"
  include_tasks: "yumInstallPrerequisitePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_prerequisite_package_install

- name: "APT - add repositories"
  when:
    - ansible_pkg_mgr == "apt"
    - aspects_packages_add_repo_apt_repos is defined
  include_tasks: "aptAddRepository.yml"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_apt

- name: "YUM - add repositories"
  when:
    - ansible_pkg_mgr == "yum"
    - aspects_packages_add_repo_yum_repos is defined
  include_tasks: "yumAddRepository.yml"
  tags:
    - aspects_packages
    - aspects_packages_add_repo_yum

- name: "APT - install packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptInstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_install

- name: "YUM - install packages"
  when:
    - ansible_pkg_mgr == "yum"
  include_tasks: "yumInstallPackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_install

- name: "APT - remove packages"
  when:
    - ansible_pkg_mgr == "apt"
  include_tasks: "aptRemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_remove

- name: "YUM - remove packages"
  when:
    - ansible_pkg_mgr == "yum"
  include_tasks: "yumRemovePackages.yml"
  tags:
    - aspects_packages
    - aspects_packages_package_remove
