---
- include_tasks: "init.yml"
  when:
    - aspects_packages_enabled
    - inprocess_aspects_packages_ran is not defined
  register: inprocess_aspects_packages_ran
  tags:
  - aspects_packages
  - aspects_packages_add_repo_apt
  - aspects_packages_add_repo_yum
  - aspects_packages_enabled
  - aspects_packages_package_install
  - aspects_packages_package_install_apt
  - aspects_packages_package_install_apt_url
  - aspects_packages_package_install_yum
  - aspects_packages_package_remove
  - aspects_packages_package_remove_yum
  - aspects_packages_prerequisite_package_install
  - aspects_packages_prerequisite_package_remove
  - aspects_packages_snap
  - aspects_packages_snap_remove
  - aspects_packages_snap_install
  - aspects_packages
  - aspects_packages_flatpack
  - aspects_packages_flatpack_remotes
  - aspects_packages_flatpack_packages