---
- name: yum - Set repository state
  yum_repository:
    state: "{{ item.value.state }}"
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    gpgkey: "{{ item.value.gpgkey }}"
    baseurl: "{{ item.value.baseurl }}"
    sslverify: "{{ item.value.sslverify }}"
    repo_gpgcheck: "{{ item.value.repo_gpgcheck }}"
    gpgcheck: "{{ item.value.gpgcheck }}"
    enabled: "{{ item.value.enabled }}"
    sslcacert: "{{ item.value.sslcacert }}"
    metadata_expire: "{{ item.value.metadata_expire }}"
  loop: "{{ aspects_packages_add_repo_yum_repos|dict2items }}"
  tags:
  - aspects_packages
  - aspects_packages_add_repo_yum